In [5]:
number = 15

In [6]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 

In [7]:
my_list = [1, 2, 3]

In [8]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

### Numpy

In [9]:
import numpy as np

In [10]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [11]:
array_a = np.array([1, 2, 3, 4])

In [12]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [13]:
array_a[0]

1

In [14]:
array_b[-1]

2.0

In [15]:
array_a[:2]

array([1, 2])

In [16]:
array_a.dtype

dtype('int32')

In [17]:
array_b.dtype

dtype('float64')

In [18]:
empty_array = np.array([])

In [19]:
empty_array.dtype

dtype('float64')

In [20]:
np.array([1 ,2 ,3 ,4], dtype=np.float_)

array([1., 2., 3., 4.])

In [21]:
np.array([1 ,2 ,3 ,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [22]:
array_t=np.array(["ada", "lovelace"])

In [23]:
array_t.dtype

dtype('<U8')

### Dimensions ans shapes


In [24]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [25]:
array_a.shape

(4,)

In [26]:
my_array.shape

(2, 3)

In [27]:
array_a.ndim

1

In [28]:
my_array.ndim

2

In [29]:
my_array.size

6

In [30]:
my_array3d =np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
         [6, 5, 4],
         [3, 2, 1]
    ]
])

In [31]:
my_array3d.ndim

3

In [32]:
my_array3d.shape

(2, 2, 3)

In [33]:
my_array3d.size

12

indexing and slicing

In [34]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [35]:
my_array[1]

array([4, 5, 6])

In [36]:
my_array[1][0]

4

In [37]:
my_array[1, 0]

4

In [38]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
my_array[:2, :2]

array([[1, 2],
       [4, 5]])

In [40]:
my_array[1] = np.array([10, 10, 10])

In [41]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [42]:
my_array[2] = 99

In [43]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [44]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [45]:
my_array = np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [48]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [50]:
np.eye(5,5) #dioganal matris

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
my_array = np.random.random((5,2))
my_array

array([[0.44548594, 0.37241219],
       [0.27241186, 0.95989622],
       [0.35747581, 0.68951634],
       [0.25120495, 0.10695353],
       [0.40426216, 0.54174031]])

In [52]:
np.random.randint(100, size =(5, 5))

array([[56, 86, 71, 67, 31],
       [64, 34, 83, 28, 61],
       [84, 72, 80, 36, 28],
       [82, 84, 55, 64, 90],
       [53, 66, 89, 74, 14]])

In [53]:
np.linspace(5,10,25)

array([ 5.        ,  5.20833333,  5.41666667,  5.625     ,  5.83333333,
        6.04166667,  6.25      ,  6.45833333,  6.66666667,  6.875     ,
        7.08333333,  7.29166667,  7.5       ,  7.70833333,  7.91666667,
        8.125     ,  8.33333333,  8.54166667,  8.75      ,  8.95833333,
        9.16666667,  9.375     ,  9.58333333,  9.79166667, 10.        ])

In [54]:
# any(), all(), full(), concatenate

arr_bool= np.array([False, False, True, False])
np.any(arr_bool) # Are true values in any methods 

True

In [55]:
np.all(arr_bool) # are true inside all values

False

In [56]:
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [99]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [102]:
np.concatenate([array1, array1], axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

#### Statistics

In [58]:
array1 = np.arange(0, 10)
array1 =array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
array1.sum()

45

In [60]:
array1.mean()

4.5

In [61]:
array1.std()

2.8722813232690143

In [62]:
array1.var()

8.25

In [63]:
array1.sum(axis=1)

array([10, 35])

In [64]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [65]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
array1 += 10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
array2 = np.arange(0, 10)
array2 =array2.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### Boolean Arrays

In [68]:
a= np.arange(4)
a

array([0, 1, 2, 3])

In [69]:
a[0], a[-1]

(0, 3)

In [70]:
a[[0, -1]]

array([0, 3])

In [71]:
a[[True, False,False,True]]

array([0, 3])

In [72]:
a >= 2    # a[:] >= 2

array([False, False,  True,  True])

In [73]:
a [ a>= 2]

array([2, 3])

In [74]:
a.mean()

1.5

In [75]:
a[a > a.mean()]

array([2, 3])

In [76]:
a[~(a > a.mean())]

array([0, 1])

In [77]:
a[ (a == 0 ) | (a==1)]

array([0, 1])

In [78]:
a [ (a <= 2) & (a % 2 == 0)]

array([0, 2])

In [79]:
# 100e kadar  rastgele olan 3,3 tam sayılardan oluşan matrix oluşturun
# 30'dan büyük olanları boolean yöntemi ile filitreleyin

my_matrix = np.random.randint(0,100, size = (3,3))
my_matrix



array([[48,  5, 75],
       [14, 77, 38],
       [76, 32, 86]])

In [80]:
boolean_array = my_matrix >30
boolean_array

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [81]:
my_matrix[ my_matrix >30]

array([48, 75, 77, 38, 76, 32, 86])

In [82]:
my_array = np. array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1=my_array.reshape(5,2)
array_2=my_array.reshape(2,5)

In [83]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [84]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
np.dot(array_1, array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [86]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [87]:
import sys

In [88]:
sys.getsizeof(10)

28

In [89]:
sys.getsizeof(1000**100)

160

In [90]:
np.dtype(int).itemsize

4

In [91]:
np.dtype(np.int8).itemsize

1

In [92]:
np.dtype(float).itemsize

8

In [93]:
sys.getsizeof([1, 2, 3])

88

In [94]:
np.array([1, 2, 3]).nbytes

12

In [95]:
my_list = list(range(100000))

In [96]:
my_array = np.arange(100000)

In [97]:
%time np.sum(my_array**2)

CPU times: total: 0 ns
Wall time: 0 ns


216474736

In [98]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 15.6 ms
Wall time: 20.7 ms


333328333350000